Type: SamplePlot
pipe:
- Type: UnPack # x,mask,(pred, out_mask) -> x,mask,pred, out_mask
- Type: Pack
  struct: [0,1,2] # x, mask, pred
##### Parse x ####################
- Type: ApplyOne
  index: 0
  pipe:
  - Type: npFunction
    fun: squeeze
  - Type: ColorMap
    cmap: gray
##### Parse y mask  ###########
- Type: ApplyOne
  index: 1
  pipe:
  - Type: npFunction
    fun: squeeze
  - Type: ColorMap
    cmap: gray
##### Parse pred mask  ###########
- Type: ApplyOne
  index: 2
  pipe:
  - Type: npFunction
    fun: squeeze
  - Type: torchFunction
    fun: sigmoid
  - Type: ColorMap
    cmap: gray
##### Combine ####################
- Type: Pack
  struct: [[0,0],[1,2]]
- Type: ApplyOne # x
  index: 0
  pipe:
  - Type: Stack
    axis: 0
- Type: ApplyOne # masks
  index: 1
  pipe:
  - Type: Stack
    axis: 0
  - Type: Dilate
    dilation: 3
- Type: Stack
  axis: 1
- Type: npFunction
  fun: transpose
  fun_args:
    axes: [2, 0, 1]